### ISSUE TITLE
Missing metadata properties

### ISSUE THREAD

**Issue by jkouvar** [OpertusMundi/profile#3] opened 2021-05-13 11:07 UTC
**Description**

Until commit 45fabab1a9fac0326d24c138870bbf376e95d1fb, metadata included several images (base64 strings) and GeoJSON properties e.g., `mbrStatic` (image), `convexHullStatic` (image), and `heatmap` (GeoJSON).

The latest release returns `null` for the aforementioned properties.

**To Reproduce**

File [nyc_roads.zip](https://github.com/OpertusMundi/profile/files/6472030/nyc_roads.zip) has been used for generating the automated metadata.

File [automated-metadata-before.zip](https://github.com/OpertusMundi/profile/files/6472029/automated-metadata-before.zip) is an example of the expected metadata returned by older versions of the service.

File [automated-metadata-after.zip](https://github.com/OpertusMundi/profile/files/6472031/automated-metadata-after.zip) is the current result.

**Comment by kPsarakis** [comment] 2021-05-13 11:29
@jkouvar I have identified the cause and currently working on it. It has to do with the changes to the temp folder logic. Additionally, I will make sure to include tests to catch nulls on the aforementioned metadata properties.

**Comment by kPsarakis** [comment] 2021-05-13 18:47
@jkouvar commit 8ad162c fixed the bug and 7350331 added a test case to catch such behavior. When you verify that it works feel free to close the issue.

**Closed as completed** 2021-05-14 10:26 UTC
Labels: bug
